export const GET_EDIT_COURSE = "GET_EDIT_COURSE";
export const GET_AUTH = "GET_AUTH";
export const CHANGE_PARAMS = "CHANGE_PARAMS";
export const GET_COURSE = "GET_COURSE";
export const ERROR = "ERROR";
export const GET_LESSON = "GET_LESSON";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";

export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const GET_ALL_PROVEN_COURSES = "GET_ALL_PROVEN_COURSES";
export const GET_ALL_UNTESTED_COURSES = "GET_ALL_UNTESTED_COURSES";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_MY_CREATED_COURSES = "GET_MY_CREATED_COURSES";
export const GET_MY_TAKE_COURSES = "GET_MY_TAKE_COURSES";
export const GET_MY_FAVORITE_COURSES = "GET_MY_FAVORITE_COURSES";
export const GET_EDIT_LESSON = "GET_EDIT_LESSON";
export const GET_USER = "GET_USER";
export const GET_MY_COMPLETED_COURSES = "GET_MY_COMPLETED_COURSES";

export const GO_EMPTY = "GO_EMPTY";

export const GET_ALL_BAN_USERS = "GET_ALL_BAN_USERS";
